# Generated by Django 4.1.2 on 2023-01-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('products', models.TimeField()),
                ('sum', models.FloatField()),
                ('condition', models.CharField(max_length=255)),
                ('paid', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('code', models.SlugField(max_length=10)),
                ('balance', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('brand_line', models.CharField(max_length=255)),
                ('generation', models.IntegerField()),
                ('arrival', models.DateField()),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('description', models.TextField()),
                ('color', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('second_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.BigIntegerField()),
            ],
        ),
    ]
