# Generated by Django 4.1.5 on 2023-01-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='descriptions',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='descriptions',
            field=models.TextField(null=True),
        ),
    ]
