# Generated by Django 4.1.5 on 2023-01-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_user_password_alter_category_descriptions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Добавлен'),
        ),
        migrations.AddField(
            model_name='user',
            name='time_update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Изменён'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.SlugField(max_length=100, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.BigIntegerField(verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='user',
            name='second_name',
            field=models.CharField(max_length=100, verbose_name='Фамилия'),
        ),
    ]
