# Generated by Django 4.1.5 on 2023-01-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_user_time_create_user_time_update_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Добавлена'),
        ),
        migrations.AddField(
            model_name='category',
            name='time_update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Изменена'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Добавлена'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='time_update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Изменена'),
        ),
    ]
