# Generated by Django 4.1.5 on 2023-01-08 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_category_time_create_category_time_update_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='descriptions',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='descriptions',
        ),
    ]
