# Generated by Django 4.1.5 on 2023-01-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_user_adress_alter_category_name_alter_user_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='adress',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='user',
            name='second_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Фамилия'),
        ),
    ]
