# Generated by Django 4.1.5 on 2023-01-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_user_second_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(help_text='8 - 20 знаков. A-Z, a-z, 0-9, спецсимволы.', max_length=20, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(help_text='Только цифры с кодом, например: 375291234567', verbose_name='Мобильный телефон (А1, МТС, life)'),
        ),
    ]
