# Generated by Django 4.1.5 on 2023-01-09 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(default='-', max_length=20, verbose_name='Код товара'),
        ),
    ]
