# Generated by Django 4.1.5 on 2023-01-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(default='0.00', verbose_name='Цена'),
        ),
    ]
