# Generated by Django 4.1.5 on 2023-01-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_user_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='code',
        ),
        migrations.AddField(
            model_name='product',
            name='article_number',
            field=models.CharField(default='', max_length=20, verbose_name='Артикул'),
        ),
        migrations.AddField(
            model_name='product',
            name='code_number',
            field=models.CharField(default='', max_length=20, verbose_name='Код товара'),
        ),
        migrations.AlterField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(blank=True, to='shop.product'),
        ),
    ]
