# Generated by Django 4.1.5 on 2023-01-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_remove_product_code_product_article_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['category', 'brand', 'name'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AddField(
            model_name='subcategory',
            name='single_name',
            field=models.CharField(db_index=True, default='', max_length=100, verbose_name='Штучное наименование'),
        ),
    ]
