# Generated by Django 4.1.5 on 2023-01-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_alter_product_options_subcategory_single_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='single_name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Штучное наименование'),
        ),
    ]
