# Generated by Django 4.1.5 on 2023-01-15 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_remove_product_code_number_alter_brand_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='second_name',
            new_name='last_name',
        ),
    ]
