# Generated by Django 4.1.5 on 2023-01-17 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_alter_product_image_alter_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
