# Generated by Django 4.1.5 on 2023-01-20 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_remove_product_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
