# Generated by Django 4.1.5 on 2023-03-15 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0043_alter_product_brand_alter_product_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.BigIntegerField(unique=True, verbose_name='ID покупателя')),
                ('customer_comment', models.TextField(blank=True, verbose_name='Комментарий покупателя')),
                ('manager_comment', models.TextField(blank=True, verbose_name='Комментарий менеджера')),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Общая стоимость заказа')),
                ('time_create', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Добавлен')),
                ('time_update', models.DateTimeField(auto_now=True, null=True, verbose_name='Изменён')),
                ('status', models.CharField(blank=True, choices=[('OCFD', 'Заказ собран для доставки'), ('OWTC', 'Заказ в пути к покупателю')], max_length=4, verbose_name='Статус')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачен')),
                ('is_delivered', models.BooleanField(default=False, verbose_name='Доставлен')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.BigIntegerField(unique=True, verbose_name='ID товара')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Цена товара')),
                ('product_quantity', models.IntegerField(verbose_name='Количество товара')),
                ('product_total_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая стоимость товара')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.order')),
            ],
            options={
                'verbose_name': 'Товары в заказе',
                'verbose_name_plural': 'Товары в заказе',
            },
        ),
    ]
