# Generated by Django 4.1.5 on 2023-03-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0044_order_ordercontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_id',
            field=models.BigIntegerField(verbose_name='ID покупателя'),
        ),
    ]
