# Generated by Django 4.1.5 on 2023-03-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0046_alter_ordercontent_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercontent',
            name='product_id',
            field=models.BigIntegerField(verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ordercontent',
            name='product_price',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='ordercontent',
            name='product_quantity',
            field=models.IntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='ordercontent',
            name='product_total_value',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая стоимость'),
        ),
    ]
