# Generated by Django 4.1.5 on 2023-03-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0048_alter_order_total_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_value',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cумма'),
        ),
    ]
